// <auto-generated />
using System;
using FinanceControl.DebtService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceControl.DebtService.Persistence.Migrations
{
    [DbContext(typeof(DebtDbContext))]
    [Migration("20260803120758_AddSimplifiedSettlementPlans")]
    partial class AddSimplifiedSettlementPlans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceControl.DebtService.Domain.Debt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("PaidByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("paid_by_person_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(19, 2)
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_debts_created_by_user_id");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("ix_debts_due_date");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_debts_group_id");

                    b.HasIndex("PaidByPersonId")
                        .HasDatabaseName("ix_debts_paid_by_person_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_debts_status");

                    b.ToTable("debts", (string)null);
                });

            modelBuilder.Entity("FinanceControl.DebtService.Domain.DebtGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_debt_groups_created_by");

                    b.ToTable("debt_groups", (string)null);
                });

            modelBuilder.Entity("FinanceControl.DebtService.Domain.DebtGroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DebtGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("debt_group_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_debt_group_members_user_id");

                    b.HasIndex("DebtGroupId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_debt_group_members_group_user");

                    b.ToTable("debt_group_members", (string)null);
                });

            modelBuilder.Entity("FinanceControl.DebtService.Domain.DebtHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DebtId")
                        .HasColumnType("uuid")
                        .HasColumnName("debt_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("DebtId", "OccurredAt")
                        .HasDatabaseName("ix_debt_history_debt_occurred_at");

                    b.ToTable("debt_history", (string)null);
                });

            modelBuilder.Entity("FinanceControl.DebtService.Domain.DebtShare", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 2)
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("DebtId")
                        .HasColumnType("uuid")
                        .HasColumnName("debt_id");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(19, 2)
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("paid_amount");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_debt_shares_person_id");

                    b.HasIndex("DebtId", "PersonId")
                        .IsUnique()
                        .HasDatabaseName("ux_debt_shares_debt_person");

                    b.ToTable("debt_shares", null, t =>
                        {
                            t.HasCheckConstraint("ck_debt_shares_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_debt_shares_paid_amount_range", "paid_amount >= 0 AND paid_amount <= amount");
                        });
                });

            modelBuilder.Entity("FinanceControl.DebtService.Domain.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddresseeDisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("addressee_display_name");

                    b.Property<string>("AddresseeEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("addressee_email");

                    b.Property<Guid>("AddresseeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("addressee_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PairKey")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("character varying(65)")
                        .HasColumnName("pair_key");

                    b.Property<string>("RequesterDisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("requester_display_name");

                    b.Property<string>("RequesterEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("requester_email");

                    b.Property<Guid>("RequesterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PairKey")
                        .IsUnique()
                        .HasDatabaseName("ux_friendships_pair_key");

                    b.HasIndex("AddresseeUserId", "Status")
                        .HasDatabaseName("ix_friendships_addressee_status");

                    b.HasIndex("RequesterUserId", "Status")
                        .HasDatabaseName("ix_friendships_requester_status");

                    b.ToTable("friendships", (string)null);
                });

            modelBuilder.Entity("FinanceControl.DebtService.Domain.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 2)
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("ConfirmationRequiredFromUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmation_required_from_user_id");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DebtId")
                        .HasColumnType("uuid")
                        .HasColumnName("debt_id");

                    b.Property<Guid>("DebtShareId")
                        .HasColumnType("uuid")
                        .HasColumnName("debt_share_id");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DebtId")
                        .HasDatabaseName("ix_payments_debt_id");

                    b.HasIndex("DebtShareId")
                        .HasDatabaseName("ix_payments_debt_share_id");

                    b.HasIndex("ConfirmationRequiredFromUserId", "Status")
                        .HasDatabaseName("ix_payments_confirmation_user_status");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_payments_amount_positive", "amount > 0");
                        });
                });

            modelBuilder.Entity("FinanceControl.DebtService.Domain.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("IsCurrentUser")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current_user");

                    b.Property<Guid?>("LinkedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LinkedUserId")
                        .HasDatabaseName("ix_people_linked_user_id");

                    b.HasIndex("OwnerUserId", "Email")
                        .HasDatabaseName("ix_people_owner_email");

                    b.HasIndex("OwnerUserId", "IsCurrentUser")
                        .IsUnique()
                        .HasDatabaseName("ux_people_current_user")
                        .HasFilter("is_current_user = TRUE");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("FinanceControl.DebtService.Domain.SettlementAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 2)
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("DebtId")
                        .HasColumnType("uuid")
                        .HasColumnName("debt_id");

                    b.Property<Guid>("DebtShareId")
                        .HasColumnType("uuid")
                        .HasColumnName("debt_share_id");

                    b.Property<Guid>("SettlementPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("settlement_plan_id");

                    b.HasKey("Id");

                    b.HasIndex("DebtId")
                        .HasDatabaseName("ix_settlement_allocations_debt_id");

                    b.HasIndex("DebtShareId")
                        .HasDatabaseName("ix_settlement_allocations_debt_share_id");

                    b.HasIndex("SettlementPlanId");

                    b.ToTable("settlement_allocations", null, t =>
                        {
                            t.HasCheckConstraint("ck_settlement_allocations_amount_positive", "amount > 0");
                        });
                });

            modelBuilder.Entity("FinanceControl.DebtService.Domain.SettlementPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_settlement_plans_created_by_user_id");

                    b.HasIndex("GroupId", "Status")
                        .HasDatabaseName("ix_settlement_plans_group_status");

                    b.ToTable("settlement_plans", (string)null);
                });

            modelBuilder.Entity("FinanceControl.DebtService.Domain.SettlementTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 2)
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FromIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_identity_id");

                    b.Property<Guid>("FromPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_person_id");

                    b.Property<string>("FromPersonName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("from_person_name");

                    b.Property<Guid?>("FromUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_user_id");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<Guid?>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<Guid>("SettlementPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("settlement_plan_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("ToIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_identity_id");

                    b.Property<Guid>("ToPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_person_id");

                    b.Property<string>("ToPersonName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("to_person_name");

                    b.Property<Guid?>("ToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_user_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId")
                        .HasDatabaseName("ix_settlement_transfers_from_user_id");

                    b.HasIndex("SettlementPlanId");

                    b.HasIndex("ToUserId", "Status")
                        .HasDatabaseName("ix_settlement_transfers_to_user_status");

                    b.ToTable("settlement_transfers", null, t =>
                        {
                            t.HasCheckConstraint("ck_settlement_transfers_amount_positive", "amount > 0");
                        });
                });

            modelBuilder.Entity("FinanceControl.DebtService.Domain.Debt", b =>
                {
                    b.HasOne("FinanceControl.DebtService.Domain.DebtGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinanceControl.DebtService.Domain.Person", "PaidByPerson")
                        .WithMany()
                        .HasForeignKey("PaidByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("PaidByPerson");
                });

            modelBuilder.Entity("FinanceControl.DebtService.Domain.DebtGroupMember", b =>
                {
                    b.HasOne("FinanceControl.DebtService.Domain.DebtGroup", null)
                        .WithMany("Members")
                        .HasForeignKey("DebtGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceControl.DebtService.Domain.DebtHistory", b =>
                {
                    b.HasOne("FinanceControl.DebtService.Domain.Debt", null)
                        .WithMany("History")
                        .HasForeignKey("DebtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceControl.DebtService.Domain.DebtShare", b =>
                {
                    b.HasOne("FinanceControl.DebtService.Domain.Debt", null)
                        .WithMany("Shares")
                        .HasForeignKey("DebtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceControl.DebtService.Domain.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FinanceControl.DebtService.Domain.Payment", b =>
                {
                    b.HasOne("FinanceControl.DebtService.Domain.Debt", null)
                        .WithMany("Payments")
                        .HasForeignKey("DebtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceControl.DebtService.Domain.DebtShare", "DebtShare")
                        .WithMany()
                        .HasForeignKey("DebtShareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DebtShare");
                });

            modelBuilder.Entity("FinanceControl.DebtService.Domain.SettlementAllocation", b =>
                {
                    b.HasOne("FinanceControl.DebtService.Domain.SettlementPlan", null)
                        .WithMany("Allocations")
                        .HasForeignKey("SettlementPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceControl.DebtService.Domain.SettlementTransfer", b =>
                {
                    b.HasOne("FinanceControl.DebtService.Domain.SettlementPlan", null)
                        .WithMany("Transfers")
                        .HasForeignKey("SettlementPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceControl.DebtService.Domain.Debt", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Payments");

                    b.Navigation("Shares");
                });

            modelBuilder.Entity("FinanceControl.DebtService.Domain.DebtGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("FinanceControl.DebtService.Domain.SettlementPlan", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Transfers");
                });
#pragma warning restore 612, 618
        }
    }
}
